### ISSUE TITLE
Error when tagging a tweet

### ISSUE THREAD

**Issue by prtksxna** [winkjs/wink-pos-tagger#22]
When running the following code on Runkit:
```javascript
// Load wink-pos-tagger.
var posTagger = require( 'wink-pos-tagger' );

// Create an instance of the pos tagger.
var tagger = posTagger();

// Tag the sentence using the tag sentence api.
tagger.tagSentence( '@FeminismInIndiaðŸ‘§ conducted a workshop at #AmbedkarUniversity on "online safety" recently:-)! reach us at info@feminisminindia.com. #DigitalSaftey http://bit.ly/2F2m9rL' );
```

I get the following error:
<img width="555" alt="screen shot 2018-02-27 at 12 56 18 pm" src="https://user-images.githubusercontent.com/9491/36715768-a4aca8f2-1bbd-11e8-895a-04fb74fd2f1e.png">

**Comment by sanjayaksaxena** [comment]
### Cause
This occurred because some punctuation tagged as punctuation by [tokenizer](https://github.com/winkjs/wink-tokenizer/) are currently not mapped to a `pos` in [lexicon](https://github.com/winkjs/wink-lexicon/blob/master/src/punctuations.js)

**and**

The junk chars adjacent to `@mention` do contain one such punctuation `‘`.

### Proposed Solution
1. Add a catch all in the `unigram-tagger` where punctuation is handled i.e.  at `token.tag === 'punctuation'` check.
2. Add a more mappings in [lexicon](https://github.com/winkjs/wink-lexicon/blob/master/src/punctuations.js) & *keep the two package in sync*.

**Comment by sanjayaksaxena** [comment]
This issue has already been raised via issue #18 

Closing #18 and will keep this active!
