### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by daoan1412** [winkjs/wink-pos-tagger#33]
I can't build my react native app with wink-pos-tagger.
It seems that it does not support react-native ?

**Comment by rachnachakraborty** [comment]
Hi @daoan1412

Since all wink packages are targeted for node, you may be required to use tools like [browserify](https://github.com/browserify/browserify-handbook). This has been discussed in issues at [react-native repo](https://github.com/facebook/react-native/):

1. [[Packager] should use compatible versions of node core modules]()https://github.com/facebook/react-native/issues/1871
2. [[Packager] Global require replace](https://github.com/facebook/react-native/issues/6253)

You can also lookup stackoverflow for possible methods. 

Hope it helps. If you let us know the exact nature of your problem, we may be able to assist you further.

Best,
Rachna

**Comment by sanjayaksaxena** [comment]
Hi @daoan1412

Hope your problem is solved... closing the issue for now.

Best,
Sanjaya

**Comment by daoan1412** [comment]
I have used nodejs-mobile to solve this problem. Thanks for your support!
