### ISSUE TITLE
wink-helpers/src/wink-helpers.js:490     str.toLowerCase().normalize( 'NFD' ).replace( rgxDiacritical, '' ) - TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by giorgio79** [winkjs/wink-pos-tagger#34]
Looks like wink is choking on the slanted apostrophe character
```
'we',
  '’',
  're',

```
runkit demo at https://runkit.com/giorgio79/5c1115662090190012ea4757

**Comment by sanjayaksaxena** [comment]
Hello @giorgio79 

Please use `tagger.tagSentence( "we’re" )` instead of `tag()`. The `tag()` API requires tokens in the format generated by [`wink-tokenizer`](https://www.npmjs.com/package/wink-tokenizer); its documentation needs a fix. Will do the needful separately.

Thanks for spotting the documentation bug.

Best,
Sanjaya

**Comment by giorgio79** [comment]
Much appreciated.
