### ISSUE TITLE
word incorrectly tagged as adjective (JJ)

### ISSUE THREAD

**Issue by gezquinndesign** [winkjs/wink-pos-tagger#41]
The sentence "I can't find my other sandal" results in the following tags:
```
[{value: "I", tag: "word", normal: "i", pos: "PRP"}
,{value: "ca", tag: "word", normal: "ca", pos: "MD", lemma: "can"}
,{value: "n't", tag: "word", normal: "n't", pos: "RB", lemma: "not"}
,{value: "find", tag: "word", normal: "find", pos: "VB", lemma: "find"}
,{value: "my", tag: "word", normal: "my", pos: "PRP$"}
,{value: "other", tag: "word", normal: "other", pos: "JJ", lemma: "other"}
,{value: "sandal", tag: "word", normal: "sandal", pos: "JJ", lemma: "sandal"}]
```
sandal should be a noun not an adjective.

**Comment by sanjayaksaxena** [comment]
Hi @gezquinndesign 

Such instances occur due to Out Of Vocabulary (OOV) words; and **sandal** is one of them! For OOV words, it applies [morphological rules](https://github.com/winkjs/wink-lexicon/blob/master/src/unknown-words.js) to *guess* the pos tag — which is why it is being tagged as JJ.

To handle such situations, `wink-pos-tagger` provides an [`updateLexicon()`](https://winkjs.org/wink-pos-tagger/Tagger.html#updateLexicon) API. You can easily add OOV words that are required for your domain to the tagger.

Hope it will solve the problem.

Best,
Sanjaya

**Comment by gezquinndesign** [comment]
Thanks for the reply. That's good to know. Out of interest, how many words are currently in the lexicon and how does that equate to file size? 

Is it possible to extend the morphological rules?

Also, how many languages are supported at the moment?

**Comment by rachnachakraborty** [comment]
Hi @gezquinndesign 

There are about 13500 words in the lexicon used by the pos tagger and it supports only English. There is no API to update the morphological rules — these have been statistically derived and it may not be a good idea to modify them unless there is a specific use case.

Currently [wink-tokenizer](https://github.com/winkjs/wink-tokenizer) and [wink-ner](https://github.com/winkjs/wink-ner) support multiple languages such as English, French to Hindi and Marathi.

Just to update you, we are working on a next generation [wink-nlp](https://github.com/winkjs/wink-nlp) with features like developer friendly APIs, plug-n-play statistical models and word vectors integration, with support for multiple languages.

Shall keep you posted.

Best,
Rachna
